"""
bootstrap_swap — Bootstrap a :class:`DiscountCurve` from par swap rates.

**Overview**
------------
Given an ordered ladder of par swap quotes (each a tenor and a fixed rate
that sets NPV to zero at inception), this module solves for the unique set
of discount factors that are consistent with all quoted par rates
simultaneously.

**Bootstrapping method (algebraic, no root-find)**
---------------------------------------------------
For a spot-starting vanilla swap with payment frequency *f*, n coupon
dates t₁ < … < tₙ, accrual fractions τᵢ, and the par-floating
approximation for the floating leg (PV_float = 1 − df(tₙ) for a spot
swap), the par condition is:

    PV_fixed = PV_float
    par_rate × Σᵢ τᵢ × df(tᵢ)  +  df(tₙ)  =  1

After solving the discount factors for all maturities shorter than tₙ
from previous bootstrap steps, the **only unknown** is df(tₙ).  Rearranging:

    df(tₙ) × (1 + par_rate × τₙ)
        =  1 − par_rate × Σᵢ₌₁ᴺ⁻¹ τᵢ × df(tᵢ)

    df(tₙ)  =  (1 − par_rate × Σᵢ₌₁ᴺ⁻¹ τᵢ × df(tᵢ))
               ─────────────────────────────────────────
               (1 + par_rate × τₙ)

This is a direct formula — one evaluation per tenor, no iteration.

The resulting ``DiscountCurve`` stores exactly one pillar per quoted
maturity.  Dates inside the bootstrap that fall between quoted maturities
are interpolated by ``DiscountCurve.df()`` using log-linear interpolation
on the already-solved pillars.

**Conventions and assumptions**
--------------------------------
- All swaps are spot-starting: ``start_date == valuation_date``.
- Coupon schedule generated by
  :func:`~quant_core.conventions.schedule.generate_unadjusted_dates`
  (no business-day adjustment in this step).
- Floating leg uses the par-floating approximation:
  ``PV_float = notional × (1 − df(maturity))``.
- Day-count convention applies uniformly to the fixed-leg accrual
  fractions.
- One discount/forecast curve; no OIS/LIBOR split.
"""
from __future__ import annotations

import math
from datetime import date
from typing import Sequence

from quant_core.conventions.day_count import DayCount, accrual_fraction
from quant_core.conventions.schedule import generate_unadjusted_dates
from quant_core.curves.discount_curve import DiscountCurve
from quant_core.schemas.market_inputs import ParSwapQuote


def bootstrap_discount_curve_from_swaps(
    valuation_date: date,
    swap_quotes: Sequence[ParSwapQuote],
    payment_frequency: str = "annual",
    day_count: DayCount = DayCount.ACT_365F,
) -> DiscountCurve:
    """
    Bootstrap a :class:`~quant_core.curves.discount_curve.DiscountCurve`
    from a ladder of par vanilla-swap quotes.

    Each quote is a par rate for a spot-starting fixed-for-floating swap
    of the given tenor.  The bootstrap solves discount factors sequentially
    from the shortest to the longest tenor using the algebraic par-swap
    identity — no numerical root-finding is required.

    Parameters
    ----------
    valuation_date : date
        As-of / settlement date.  All swaps are assumed to start on this
        date.
    swap_quotes : sequence of ParSwapQuote
        Par swap quotes.  May be supplied in any order — they are sorted
        by ``tenor_years`` ascending inside this function.  Must be
        non-empty.  Duplicate tenors are rejected.
    payment_frequency : str, optional
        Fixed-leg coupon frequency — one of ``"monthly"``, ``"quarterly"``,
        ``"semiannual"``, ``"annual"`` (case-insensitive).  Defaults to
        ``"annual"``.
    day_count : DayCount, optional
        Day-count convention for fixed-leg accrual fractions.  Defaults to
        :attr:`DayCount.ACT_365F`.

    Returns
    -------
    DiscountCurve
        A :class:`~quant_core.curves.discount_curve.DiscountCurve` with
        one pillar per quoted maturity.  Pillar dates are the unadjusted
        maturity dates of the quoted swaps.

    Raises
    ------
    ValueError
        * If ``swap_quotes`` is empty.
        * If any two quotes share the same ``tenor_years`` (duplicates).
        * If a solved discount factor is not positive (implies inconsistent
          or arbitrage-violating input rates).
        * If the solved discount factors are not non-increasing with tenor
          (i.e. implied forward rates are negative — a signal of bad inputs
          rather than a supported exotic curve shape).

    Notes
    -----
    The pillar at each maturity is the *last* coupon date generated by
    :func:`~quant_core.conventions.schedule.generate_unadjusted_dates`
    for that tenor.  For ``payment_frequency="annual"`` and a whole-year
    tenor this equals ``valuation_date + tenor_years × 12 months``
    exactly (the maturity date).

    For intermediate coupon dates (those between the current and the
    next quoted maturity), the ``DiscountCurve`` log-linear interpolation
    provides a continuous df curve that is used to evaluate the annuity
    sum in the bootstrap equation for subsequent longer-tenor quotes.

    Examples
    --------
    >>> from datetime import date
    >>> from quant_core.schemas.market_inputs import ParSwapQuote
    >>> from quant_core.conventions.day_count import DayCount
    >>> from quant_core.curves.bootstrap_swap import (
    ...     bootstrap_discount_curve_from_swaps,
    ... )
    >>> val = date(2024, 1, 1)
    >>> quotes = [
    ...     ParSwapQuote(1, 0.08),
    ...     ParSwapQuote(2, 0.081),
    ... ]
    >>> curve = bootstrap_discount_curve_from_swaps(val, quotes)
    >>> len(curve.pillar_dates)
    2
    """
    # ------------------------------------------------------------------ #
    # Input validation                                                    #
    # ------------------------------------------------------------------ #
    quotes_list = list(swap_quotes)
    if not quotes_list:
        raise ValueError("swap_quotes must be non-empty")

    # Sort by tenor ascending and check for duplicates.
    quotes_list.sort(key=lambda q: q.tenor_years)
    for i in range(1, len(quotes_list)):
        if quotes_list[i].tenor_years == quotes_list[i - 1].tenor_years:
            raise ValueError(
                f"Duplicate tenor_years {quotes_list[i].tenor_years!r} in "
                f"swap_quotes; each tenor must appear exactly once"
            )

    # ------------------------------------------------------------------ #
    # Sequential algebraic bootstrap                                      #
    # ------------------------------------------------------------------ #
    # We accumulate solved (pillar_date, df) pairs as we go.
    # After each step the interim DiscountCurve is extended at the new
    # maturity date being solved.
    #
    # For quote k (tenor T_k), the coupon dates are t₁, …, tₙ where tₙ is
    # the maturity of swap k.  Coupon dates tᵢ ≤ last working pillar are
    # served by DiscountCurve log-linear interpolation.
    #
    # When all intermediate coupon dates tᵢ (i < n) lie within the working
    # curve's range, the bootstrap equation is a simple algebraic formula:
    #   df(tₙ) = (1 − c × A_prev) / (1 + c × τₙ)
    # where A_prev = Σᵢ₌₁ᴺ⁻¹ τᵢ × df(tᵢ) and τₙ = accrual_fraction of the
    # final period.
    #
    # When there are "gap" coupon dates — intermediate dates strictly between
    # the last working pillar and the current maturity (e.g. the 4Y coupon
    # date when processing a 5Y quote on a 1Y/2Y/3Y/5Y ladder) — those dates
    # will be log-linearly interpolated on the final curve between the last
    # working pillar and df(tₙ) itself.  This creates a coupled equation in
    # df(tₙ).  We solve it numerically using Newton's method so that the
    # resulting curve exactly reprices every quoted swap.

    pillar_dates: list[date] = []
    discount_factors: list[float] = []
    # _working_curve is None until the first pillar is solved.
    _working_curve: DiscountCurve | None = None

    for quote in quotes_list:
        payment_dates = generate_unadjusted_dates(
            valuation_date, quote.tenor_years, payment_frequency
        )
        # period_starts[i] is the accrual start for payment_dates[i]
        period_starts = [valuation_date] + payment_dates[:-1]
        n = len(payment_dates)
        maturity_date = payment_dates[-1]  # = last pillar we will solve now

        c = quote.par_rate

        # Pre-compute accrual fractions for all periods.
        taus = [
            accrual_fraction(period_starts[i], payment_dates[i], day_count)
            for i in range(n)
        ]

        # Detect gap dates: intermediate coupon dates (i < n-1) that fall
        # strictly beyond the last working pillar.  These require coupled
        # solving because df at those dates depends on the unknown df(tₙ).
        if _working_curve is not None:
            last_pillar = _working_curve.pillar_dates[-1]
            first_pillar = _working_curve.pillar_dates[0]
        else:
            last_pillar = None
            first_pillar = None

        has_gap = _working_curve is not None and any(
            payment_dates[i] > last_pillar  # type: ignore[operator]
            for i in range(n - 1)
        )

        def _df_for_intermediate(i: int, df_terminal: float) -> float:
            """
            Return the discount factor for intermediate coupon date
            ``payment_dates[i]`` (where i < n−1).

            If ``has_gap`` and the date is a gap date (beyond last working
            pillar), we log-linearly interpolate between the last working
            pillar and ``df_terminal`` at ``maturity_date``.  All other
            cases use the working curve or simple-rate approximation.
            """
            pd = payment_dates[i]
            if _working_curve is None:
                # No pillars yet — use simple-rate approximation.
                tau_from_val = accrual_fraction(valuation_date, pd, day_count)
                return 1.0 / (1.0 + c * tau_from_val)

            if pd > last_pillar:  # type: ignore[operator]
                # Gap date: interpolate between last known pillar and
                # the terminal pillar being solved.
                t_last = _working_curve.pillar_dates[-1]
                df_last = _working_curve.discount_factors[-1]
                total_tau = accrual_fraction(t_last, maturity_date, day_count)
                frac_tau = accrual_fraction(t_last, pd, day_count)
                # Log-linear: ln(df) = ln(df_last) + frac × (ln(df_term) − ln(df_last))
                alpha = frac_tau / total_tau
                return math.exp(
                    (1.0 - alpha) * math.log(df_last) + alpha * math.log(df_terminal)
                )

            if pd < first_pillar:  # type: ignore[operator]
                # Before-first-pillar: log-linear from val (df=1) to
                # first pillar.
                t_first = _working_curve.pillar_dates[0]
                df_first = _working_curve.discount_factors[0]
                tau_val_first = accrual_fraction(valuation_date, t_first, day_count)
                fwd_first = -math.log(df_first) / tau_val_first
                tau_val_i = accrual_fraction(valuation_date, pd, day_count)
                return math.exp(-fwd_first * tau_val_i)

            # Within the working curve range — use log-linear interpolation.
            return _working_curve.df(pd)

        def _par_residual(df_terminal: float) -> float:
            """Par-swap residual: should equal zero for the correct df_terminal."""
            annuity = sum(
                taus[i] * _df_for_intermediate(i, df_terminal)
                for i in range(n - 1)
            )
            return c * (annuity + taus[-1] * df_terminal) + df_terminal - 1.0

        # ---------------------------------------------------------------- #
        # Solve for df_terminal                                             #
        # ---------------------------------------------------------------- #
        if not has_gap:
            # No gap: the par condition is linear in df_terminal → algebraic.
            annuity_prev = sum(
                taus[i] * _df_for_intermediate(i, 0.0)  # df_terminal unused
                for i in range(n - 1)
            )
            numerator = 1.0 - c * annuity_prev
            denominator = 1.0 + c * taus[-1]
            df_new = numerator / denominator
        else:
            # Gap present: solve the coupled equation using Newton's method.
            # Initial guess from flat-forward extrapolation.
            t_last = _working_curve.pillar_dates[-1]  # type: ignore[union-attr]
            df_last = _working_curve.discount_factors[-1]  # type: ignore[union-attr]
            if len(_working_curve.pillar_dates) >= 2:  # type: ignore[union-attr]
                t_prev = _working_curve.pillar_dates[-2]  # type: ignore[union-attr]
                df_prev_h = _working_curve.discount_factors[-2]  # type: ignore[union-attr]
                tau_last_seg = accrual_fraction(t_prev, t_last, day_count)
                fwd_h = (math.log(df_prev_h) - math.log(df_last)) / tau_last_seg
            else:
                tau_to_last = accrual_fraction(valuation_date, t_last, day_count)
                fwd_h = -math.log(df_last) / tau_to_last
            tau_extrap = accrual_fraction(t_last, maturity_date, day_count)
            df_new = df_last * math.exp(-fwd_h * tau_extrap)

            # Newton's method — converges in ~5–10 iterations.
            for _ in range(50):
                f = _par_residual(df_new)
                if abs(f) < 1e-14:
                    break
                # Numerical derivative
                eps = df_new * 1e-7
                f_plus = _par_residual(df_new + eps)
                df_prime = (f_plus - f) / eps
                if abs(df_prime) < 1e-30:
                    break
                df_new -= f / df_prime

        # Guard against degenerate / arbitrage-violating inputs.
        if df_new <= 0.0:
            raise ValueError(
                f"Bootstrap produced a non-positive discount factor "
                f"({df_new:.6f}) at tenor {quote.tenor_years}Y "
                f"(maturity {maturity_date}).  Check input par rates for "
                f"arbitrage or extreme values."
            )
        if pillar_dates and df_new > discount_factors[-1]:
            raise ValueError(
                f"Bootstrap produced an increasing discount factor at tenor "
                f"{quote.tenor_years}Y: df={df_new:.6f} > previous "
                f"df={discount_factors[-1]:.6f}.  This implies a negative "
                f"implied forward rate; check input par rates."
            )

        pillar_dates.append(maturity_date)
        discount_factors.append(df_new)

        # For the first quoted tenor (no prior working curve), any intermediate
        # coupon dates that were bootstrapped via simple-rate approximation
        # must also become pillars so that the final curve can reprice the swap.
        # We insert them in chronological order before maturity_date.
        if len(pillar_dates) == 1 and n > 1:
            # n > 1 means sub-annual frequency with more than one coupon.
            # Re-compute the approximate dfs for each intermediate date,
            # then insert them as leading pillars.
            intermediate_dates: list[date] = []
            intermediate_dfs: list[float] = []
            for i in range(n - 1):
                pd = payment_dates[i]
                tau_from_val = accrual_fraction(valuation_date, pd, day_count)
                df_inter = 1.0 / (1.0 + c * tau_from_val)
                intermediate_dates.append(pd)
                intermediate_dfs.append(df_inter)
            # Re-build pillar_dates and discount_factors with intermediates first.
            pillar_dates = intermediate_dates + pillar_dates
            discount_factors = intermediate_dfs + discount_factors

        # Rebuild the working curve to include the newly solved pillar so
        # that subsequent tenors can interpolate through it.
        _working_curve = DiscountCurve(valuation_date, pillar_dates, discount_factors)

    return _working_curve  # type: ignore[return-value]  # loop always runs (non-empty validated above)
